import { Poppins, Nunito } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
    variable :"--font-poppins", 
    subsets:["latin"],
    weight:["400", "500", "600", "700"]
})
const nunito = Nunito({
    variable :"--font-nunito", 
    subsets:["latin"],
    weight:["400", "500", "600", "700"]
})
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "CI/CD",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable , nunito.variable} antialiased`}
      >
 
        {children}
      
      </body>
    </html>
  );
}
